#!/bin/sh

set -e

cd `dirname $0`

# Suck a bit fat cock, Ubuntu, there was no fucking reason to rename
# packages and break everything.
release=`lsb_release --short --codename`
if [ $release = zesty -o $release = bionic ] ; then
    sudo apt install --yes puppet
    sudo puppet apply --verbose --modulepath=$PWD/modules $PWD/site.pp
else
    test -e /etc/init.d/puppet && sudo apt-get remove --purge puppet
    test -x /usr/bin/puppet || sudo apt-get install --yes puppet-common

    sudo puppet apply --verbose --no-listen --modulepath=$PWD/modules $PWD/site.pp
fi
